# Dockerfile

FROM tensorflow/tensorflow:1.14.0-py3

WORKDIR /root

RUN pip install google-cloud-logging
RUN pip install google-cloud-bigquery
RUN pip install pandas

ENV GCS_READ_CACHE_BLOCK_SIZE_MB=16

COPY trainer.py trainer.py
